server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8

spring:
    datasource:
        name: easypro4
        url: jdbc:mysql://47.105.189.247:3306/jyweb?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    freemarker:
      allow-request-override: false
      cache: false
      check-template-location: true
      charset: UTF-8
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: false
    cache:
      type: REDIS
      redis:
        cache-null-values: false
        time-to-live: 600000ms
        use-key-prefix: true


    http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
      multipart:
        max-file-size: 100Mb
        max-request-size: 1000Mb

    jmx:
      enabled: false
    output:
      ansi:
        enabled: always


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.szdtoo.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# log
#logging:
#  level:
#    com.szdtoo.mapper:INFO


fdfs:
#  webserver: 47.105.189.247:8080
  soTimeout: 1501
  connectTimeout: 601
  thumbImage:     #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 47.105.189.247:22122
    
shiro: 
  #unauthorizedUrl: /test/unauthorizedurl
  loginUrl: /unauthorizedurl
  #successUrl: /test/login
  web: 
    enabled: true

