server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8

spring:
    datasource:
        name: kang
        url: jdbc:mysql://192.168.1.129:3306/springboot_kang?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
#        url: jdbc:mysql://192.168.0.100:11129/jyweb?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
#        username: root
#        password: szdtoo123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    freemarker:
      allow-request-override: false
      cache: false
      check-template-location: true
      charset: UTF-8
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: false
    cache:
      type: REDIS
      redis:
        cache-null-values: false
        time-to-live: 600000ms
        use-key-prefix: true
    data:
      mongodb:
        database: admin
        authentication-database: userAdminAnyDatabase
        uri: mongodb://admin:123456@192.168.1.129:27017
      elasticsearch: 
        cluster-nodes: 192.168.1.129:9200


    http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
      multipart:
        max-file-size: 100Mb
        max-request-size: 1000Mb

    jmx:
      enabled: false
    output:
      ansi:
        enabled: always


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.kang.model.mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# log
logging:
  level:
    com.kang.mapper:INFO


fdfs:
  webserver: http://192.168.1.129:8080/
  soTimeout: 1501
  connectTimeout: 601
  thumbImage:     #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 192.168.1.129:22122
    
shiro: 
  #unauthorizedUrl: /test/unauthorizedurl
  loginUrl: /unauthorizedurl
  #successUrl: /test/login
  web: 
    enabled: true
    
threadpool:
  core-pool-size: 10
  max-pool-size: 20
  queue-capacity: 1000
  keep-alive-seconds: 600



